
-- ANALYTICS LAYER 


USE WAREHOUSE SAP_WH;
USE DATABASE SAP_DB;
CREATE SCHEMA IF NOT EXISTS SAP_DB.ANALYTICS;
USE SCHEMA SAP_DB.ANALYTICS;


-- DIM_DATE -- generated calendar 

CREATE OR REPLACE TABLE ANALYTICS.DIM_DATE AS
SELECT
    DATE_KEY,
    YEAR(DATE_KEY)        AS YEAR_NUM,
    QUARTER(DATE_KEY)     AS QUARTER_NUM,
    MONTH(DATE_KEY)       AS MONTH_NUM,
    MONTHNAME(DATE_KEY)   AS MONTH_NAME,
    DAY(DATE_KEY)         AS DAY_NUM,
    DAYNAME(DATE_KEY)     AS DAY_NAME,
    DAYOFWEEK(DATE_KEY)   AS DAY_OF_WEEK,
    WEEKOFYEAR(DATE_KEY)  AS WEEK_OF_YEAR,
    CASE WHEN DAYOFWEEK(DATE_KEY) IN (0,6) THEN TRUE ELSE FALSE END AS IS_WEEKEND
FROM (
    SELECT DATEADD(DAY, SEQ4(), '1994-01-01'::DATE) AS DATE_KEY -- 1994 is the first year while 2022 is the last year
    FROM TABLE(GENERATOR(ROWCOUNT => 13514))
);


-- SELECT * FROM SAP_DB.ANALYTICS.DIM_DATE
-- LIMIT 100;


-- DIM_MATERIAL -- REAL dimension now (MARA + MAKT)

CREATE OR REPLACE VIEW ANALYTICS.DIM_MATERIAL AS
SELECT
    M.MATERIAL_NUMBER,
    MK.MATERIAL_DESCRIPTION,
    M.MATERIAL_TYPE,
    M.MATERIAL_GROUP,
    M.INDUSTRY_SECTOR,
    M.BASE_UNIT,
    M.GROSS_WEIGHT,
    M.NET_WEIGHT,
    M.WEIGHT_UNIT,
    M.CREATED_DATE
FROM STAGING.STG_MARA M
LEFT JOIN STAGING.STG_MAKT MK
    ON M.MATERIAL_NUMBER = MK.MATERIAL_NUMBER
    AND MK.LANGUAGE_KEY = 'E';  -- English descriptions and filtering duplicate names



-- DIM_COMPANY_CODE -- REAL dimension now (T001)

CREATE OR REPLACE VIEW ANALYTICS.DIM_COMPANY_CODE AS
SELECT
    COMPANY_CODE,
    COMPANY_NAME,
    CITY,
    COUNTRY,
    CURRENCY AS HOME_CURRENCY
FROM STAGING.STG_T001;

-- DIM_COST_CENTER -- REAL dimension now (CSKS + CSKT)

CREATE OR REPLACE VIEW ANALYTICS.DIM_COST_CENTER AS
SELECT
    S.COST_CENTER,
    S.CONTROLLING_AREA,
    T.SHORT_TEXT,
    T.LONG_TEXT,
    S.COMPANY_CODE,
    S.BUSINESS_AREA,
    S.COST_CENTER_CATEGORY,
    S.RESPONSIBLE_PERSON,
    S.PLANT
FROM STAGING.STG_CSKS S
LEFT JOIN STAGING.STG_CSKT T
    ON S.COST_CENTER = T.COST_CENTER
   AND S.CONTROLLING_AREA = T.CONTROLLING_AREA
   AND T.LANGUAGE_KEY = 'E';


-- DIM_VENDOR -- still degenerate, no vendor master provided

CREATE OR REPLACE VIEW ANALYTICS.DIM_VENDOR AS
SELECT DISTINCT VENDOR_ID
FROM (
    SELECT VENDOR_ID FROM STAGING.STG_EKKO
    UNION SELECT VENDOR_ID FROM STAGING.STG_RBKP
)
WHERE VENDOR_ID IS NOT NULL;


-- DIM_ORDER_TYPE / DIM_SALES_ORG / DIM_CURRENCY -- still degenerate


CREATE OR REPLACE VIEW ANALYTICS.DIM_ORDER_TYPE AS
SELECT DISTINCT ORDER_TYPE, ORDER_REASON FROM STAGING.STG_VBAK WHERE ORDER_TYPE IS NOT NULL;

CREATE OR REPLACE VIEW ANALYTICS.DIM_SALES_ORG AS
SELECT DISTINCT SALES_ORG FROM (
    SELECT SALES_ORG FROM STAGING.STG_VBAK
    UNION SELECT SALES_ORG FROM STAGING.STG_VBRK
) WHERE SALES_ORG IS NOT NULL;

CREATE OR REPLACE VIEW ANALYTICS.DIM_CURRENCY AS
SELECT DISTINCT CURRENCY FROM (
    SELECT CURRENCY FROM STAGING.STG_VBAK
    UNION SELECT CURRENCY FROM STAGING.STG_EKKO
    UNION SELECT CURRENCY FROM STAGING.STG_RBKP
) WHERE CURRENCY IS NOT NULL;


-- FACT TABLES

-- SALES ORDER 

CREATE OR REPLACE VIEW ANALYTICS.FCT_SALES_ORDER_ITEM AS
SELECT
    H.SALES_DOC_ID, I.ITEM_NUMBER, H.CREATION_DATE, H.DOCUMENT_DATE,
    H.ORDER_TYPE, H.ORDER_REASON, H.SALES_ORG, H.CREATED_BY,
    I.MATERIAL_NUMBER, I.ITEM_DESCRIPTION, I.MATERIAL_GROUP, I.PLANT,
    I.ORDER_QUANTITY, I.SALES_UNIT, I.NET_AMOUNT, I.CURRENCY
FROM STAGING.STG_VBAK H
JOIN STAGING.STG_VBAP I ON H.SALES_DOC_ID = I.SALES_DOC_ID;
--

-- FCT BILLING ITEM 
CREATE OR REPLACE VIEW ANALYTICS.FCT_BILLING_ITEM AS
SELECT
    H.BILLING_DOC_ID, I.BILLING_ITEM, H.BILLING_DATE, H.BILLING_CATEGORY,
    H.SALES_ORG, H.IS_CANCELLED, H.COMPANY_CODE,
    I.MATERIAL_NUMBER, I.ITEM_DESCRIPTION, I.PLANT,
    I.BILLED_QUANTITY, I.SALES_UNIT, I.NET_AMOUNT, H.CURRENCY,
    I.REF_SALES_DOC_ID, I.REF_SALES_ITEM
FROM STAGING.STG_VBRK H
JOIN STAGING.STG_VBRP I ON H.BILLING_DOC_ID = I.BILLING_DOC_ID;

-- FACT PROCUREMENT ITEM 
CREATE OR REPLACE VIEW ANALYTICS.FCT_PROCUREMENT_ITEM AS
SELECT
    H.PO_NUMBER, I.PO_ITEM, H.CHANGED_ON, H.DOC_TYPE, H.STATUS,
    I.COMPANY_CODE, I.PLANT, I.STORAGE_LOCATION, I.MATERIAL_NUMBER,
    I.MATERIAL_GROUP, I.PO_QUANTITY, I.UNIT_OF_MEASURE, I.NET_PRICE,
    ROUND(I.PO_QUANTITY * I.NET_PRICE, 2) AS LINE_VALUE,
    H.VENDOR_ID, H.CURRENCY, H.CREATED_BY, H.PURCHASING_ORG, H.PURCHASING_GROUP
FROM STAGING.STG_EKKO H
JOIN STAGING.STG_EKPO I ON H.PO_NUMBER = I.PO_NUMBER;

-- FACT INVOICE ITEM 
CREATE OR REPLACE VIEW ANALYTICS.FCT_AP_INVOICE_ITEM AS
SELECT
    H.INVOICE_DOC_ID, H.FISCAL_YEAR, I.INVOICE_ITEM, H.DOCUMENT_DATE,
    H.POSTING_DATE, H.VENDOR_ID, H.CURRENCY, H.GROSS_AMOUNT AS HEADER_GROSS_AMOUNT,
    H.COMPANY_CODE, I.PO_NUMBER, I.PO_ITEM, I.MATERIAL_NUMBER,
    I.ITEM_AMOUNT, I.DEBIT_CREDIT_IND, I.PLANT
FROM STAGING.STG_RBKP H
JOIN STAGING.STG_RSEG I ON H.INVOICE_DOC_ID = I.INVOICE_DOC_ID AND H.FISCAL_YEAR = I.FISCAL_YEAR;


-- RECONCILIATION VIEWS

-- FACT ORDER AND BILLING

CREATE OR REPLACE VIEW ANALYTICS.VW_ORDER_VS_BILLING AS
SELECT
    O.SALES_DOC_ID, O.ITEM_NUMBER, O.MATERIAL_NUMBER, O.ORDER_QUANTITY,
    O.NET_AMOUNT AS ORDERED_AMOUNT, O.CURRENCY,
    COALESCE(SUM(B.BILLED_QUANTITY), 0) AS BILLED_QUANTITY,
    COALESCE(SUM(B.NET_AMOUNT), 0)      AS BILLED_AMOUNT,
    O.NET_AMOUNT - COALESCE(SUM(B.NET_AMOUNT), 0) AS OPEN_AMOUNT
FROM ANALYTICS.FCT_SALES_ORDER_ITEM O
LEFT JOIN ANALYTICS.FCT_BILLING_ITEM B
    ON O.SALES_DOC_ID = B.REF_SALES_DOC_ID AND O.ITEM_NUMBER = B.REF_SALES_ITEM
   AND B.IS_CANCELLED != 'X'
GROUP BY O.SALES_DOC_ID, O.ITEM_NUMBER, O.MATERIAL_NUMBER, O.ORDER_QUANTITY, O.NET_AMOUNT, O.CURRENCY;

-- FACT PROCUREMENT AND INVOICE 
CREATE OR REPLACE VIEW ANALYTICS.VW_PO_VS_INVOICE AS
SELECT
    P.PO_NUMBER, P.PO_ITEM, P.MATERIAL_NUMBER, P.PO_QUANTITY,
    P.LINE_VALUE AS PO_VALUE, P.CURRENCY,
    COALESCE(SUM(INV.ITEM_AMOUNT), 0) AS INVOICED_AMOUNT,
    P.LINE_VALUE - COALESCE(SUM(INV.ITEM_AMOUNT), 0) AS UNINVOICED_VALUE
FROM ANALYTICS.FCT_PROCUREMENT_ITEM P
LEFT JOIN ANALYTICS.FCT_AP_INVOICE_ITEM INV
    ON P.PO_NUMBER = INV.PO_NUMBER AND P.PO_ITEM = INV.PO_ITEM
GROUP BY P.PO_NUMBER, P.PO_ITEM, P.MATERIAL_NUMBER, P.PO_QUANTITY, P.LINE_VALUE, P.CURRENCY;

-- droping test data 
CREATE OR REPLACE VIEW ANALYTICS.VW_DQ_EXCLUDED_MATERIALS AS
SELECT DISTINCT
    MATERIAL_NUMBER,
    MATERIAL_DESCRIPTION,
    'Testing Data' AS EXCLUSION_REASON
FROM ANALYTICS.DIM_MATERIAL
WHERE LOWER(MATERIAL_DESCRIPTION) LIKE '%test%'
   OR LOWER(MATERIAL_DESCRIPTION) LIKE '%dummy%'
   OR LOWER(MATERIAL_DESCRIPTION) LIKE '%sample%'
   OR LOWER(MATERIAL_DESCRIPTION) LIKE '%do not use%'
   OR LOWER(MATERIAL_DESCRIPTION) IN ('zzz', 'xxx', 'n/a', 'na', 'tbd');

-- DIM MATERIAL CLEAN 
CREATE OR REPLACE VIEW ANALYTICS.DIM_MATERIAL_CLEAN AS
SELECT M.*
FROM ANALYTICS.DIM_MATERIAL M
WHERE M.MATERIAL_NUMBER NOT IN (SELECT MATERIAL_NUMBER FROM ANALYTICS.VW_DQ_EXCLUDED_MATERIALS);

-- SELECT * FROM ANALYTICS.DIM_MATERIAL_CLEAN;

-- QUICK CHECK 
SELECT COUNT(*) AS EXCLUDED_MATERIAL_COUNT FROM ANALYTICS.VW_DQ_EXCLUDED_MATERIALS;
SELECT COUNT(*) AS CLEAN_MATERIAL_COUNT FROM ANALYTICS.DIM_MATERIAL_CLEAN;



-- Quick checks
SELECT 'FCT_SALES_ORDER_ITEM' T, COUNT(*) FROM ANALYTICS.FCT_SALES_ORDER_ITEM
UNION ALL SELECT 'FCT_BILLING_ITEM', COUNT(*) FROM ANALYTICS.FCT_BILLING_ITEM
UNION ALL SELECT 'FCT_PROCUREMENT_ITEM', COUNT(*) FROM ANALYTICS.FCT_PROCUREMENT_ITEM
UNION ALL SELECT 'FCT_AP_INVOICE_ITEM', COUNT(*) FROM ANALYTICS.FCT_AP_INVOICE_ITEM
UNION ALL SELECT 'DIM_MATERIAL', COUNT(*) FROM ANALYTICS.DIM_MATERIAL
UNION ALL SELECT 'DIM_COMPANY_CODE', COUNT(*) FROM ANALYTICS.DIM_COMPANY_CODE
UNION ALL SELECT 'DIM_COST_CENTER', COUNT(*) FROM ANALYTICS.DIM_COST_CENTER;


-- ===================================================
-- DBT test cause rebuilding objects with ClientID join 
-- ===================================================

USE SCHEMA SAP_DB.ANALYTICS;
 
CREATE OR REPLACE VIEW ANALYTICS.DIM_MATERIAL AS
SELECT
    M.CLIENT_ID,
    M.MATERIAL_NUMBER,
    MK.MATERIAL_DESCRIPTION,
    M.MATERIAL_TYPE,
    M.MATERIAL_GROUP,
    M.INDUSTRY_SECTOR,
    M.BASE_UNIT,
    M.GROSS_WEIGHT,
    M.NET_WEIGHT,
    M.WEIGHT_UNIT,
    M.CREATED_DATE
FROM STAGING.STG_MARA M
LEFT JOIN STAGING.STG_MAKT MK
    ON M.CLIENT_ID = MK.CLIENT_ID
   AND M.MATERIAL_NUMBER = MK.MATERIAL_NUMBER
   AND MK.LANGUAGE_KEY = 'E';
 
CREATE OR REPLACE VIEW ANALYTICS.DIM_MATERIAL_CLEAN AS
SELECT M.*
FROM ANALYTICS.DIM_MATERIAL M
WHERE M.MATERIAL_NUMBER NOT IN (SELECT MATERIAL_NUMBER FROM ANALYTICS.VW_DQ_EXCLUDED_MATERIALS);
 
CREATE OR REPLACE VIEW ANALYTICS.DIM_COMPANY_CODE AS
SELECT
    CLIENT_ID,
    COMPANY_CODE,
    COMPANY_NAME,
    CITY,
    COUNTRY,
    CURRENCY AS HOME_CURRENCY
FROM STAGING.STG_T001;
 
CREATE OR REPLACE VIEW ANALYTICS.FCT_SALES_ORDER_ITEM AS
-- client_id joined on both keys -- sales_doc_id repeats across this
-- dataset's 3 SAP clients, same root cause as the PO number bug.
SELECT
    H.CLIENT_ID, H.SALES_DOC_ID, I.ITEM_NUMBER, H.CREATION_DATE, H.DOCUMENT_DATE,
    H.ORDER_TYPE, H.ORDER_REASON, H.SALES_ORG, H.CREATED_BY,
    I.MATERIAL_NUMBER, I.ITEM_DESCRIPTION, I.MATERIAL_GROUP, I.PLANT,
    I.ORDER_QUANTITY, I.SALES_UNIT, I.NET_AMOUNT, I.CURRENCY
FROM STAGING.STG_VBAK H
JOIN STAGING.STG_VBAP I
    ON H.CLIENT_ID = I.CLIENT_ID AND H.SALES_DOC_ID = I.SALES_DOC_ID;
 
CREATE OR REPLACE VIEW ANALYTICS.FCT_BILLING_ITEM AS
SELECT
    H.CLIENT_ID, H.BILLING_DOC_ID, I.BILLING_ITEM, H.BILLING_DATE, H.BILLING_CATEGORY,
    H.SALES_ORG, H.IS_CANCELLED, H.COMPANY_CODE,
    I.MATERIAL_NUMBER, I.ITEM_DESCRIPTION, I.PLANT,
    I.BILLED_QUANTITY, I.SALES_UNIT, I.NET_AMOUNT, H.CURRENCY,
    I.REF_SALES_DOC_ID, I.REF_SALES_ITEM
FROM STAGING.STG_VBRK H
JOIN STAGING.STG_VBRP I
    ON H.CLIENT_ID = I.CLIENT_ID AND H.BILLING_DOC_ID = I.BILLING_DOC_ID;
 
CREATE OR REPLACE VIEW ANALYTICS.VW_ORDER_VS_BILLING AS
SELECT
    O.CLIENT_ID, O.SALES_DOC_ID, O.ITEM_NUMBER, O.MATERIAL_NUMBER, O.ORDER_QUANTITY,
    O.NET_AMOUNT AS ORDERED_AMOUNT, O.CURRENCY,
    COALESCE(SUM(B.BILLED_QUANTITY), 0) AS BILLED_QUANTITY,
    COALESCE(SUM(B.NET_AMOUNT), 0)      AS BILLED_AMOUNT,
    O.NET_AMOUNT - COALESCE(SUM(B.NET_AMOUNT), 0) AS OPEN_AMOUNT
FROM ANALYTICS.FCT_SALES_ORDER_ITEM O
LEFT JOIN ANALYTICS.FCT_BILLING_ITEM B
    ON O.CLIENT_ID = B.CLIENT_ID
   AND O.SALES_DOC_ID = B.REF_SALES_DOC_ID AND O.ITEM_NUMBER = B.REF_SALES_ITEM
   AND B.IS_CANCELLED != 'X'
GROUP BY O.CLIENT_ID, O.SALES_DOC_ID, O.ITEM_NUMBER, O.MATERIAL_NUMBER, O.ORDER_QUANTITY, O.NET_AMOUNT, O.CURRENCY;
 
CREATE OR REPLACE VIEW ANALYTICS.VW_ML_O2C_CYCLE_TIME_TRAIN AS
SELECT
    O.CLIENT_ID,
    O.SALES_DOC_ID,
    O.ITEM_NUMBER,
    O.ORDER_TYPE,
    O.ORDER_REASON,
    O.SALES_ORG,
    O.MATERIAL_GROUP,
    O.CURRENCY,
    O.ORDER_QUANTITY,
    O.NET_AMOUNT,
    MONTH(O.DOCUMENT_DATE)      AS ORDER_MONTH,
    DAYOFWEEK(O.DOCUMENT_DATE)  AS ORDER_DAY_OF_WEEK,
    DATEDIFF('DAY', O.DOCUMENT_DATE, B.BILLING_DATE) AS CYCLE_DAYS
FROM ANALYTICS.FCT_SALES_ORDER_ITEM O
JOIN ANALYTICS.FCT_BILLING_ITEM B
    ON O.CLIENT_ID = B.CLIENT_ID
   AND O.SALES_DOC_ID = B.REF_SALES_DOC_ID AND O.ITEM_NUMBER = B.REF_SALES_ITEM
WHERE O.DOCUMENT_DATE IS NOT NULL
  AND B.BILLING_DATE IS NOT NULL
  AND B.IS_CANCELLED != 'X'
  AND DATEDIFF('DAY', O.DOCUMENT_DATE, B.BILLING_DATE) BETWEEN 0 AND 365;
 

-- Sanity check: confirm no fan-out inflation happened from these changes

SELECT 'FCT_SALES_ORDER_ITEM' AS TBL, COUNT(*) FROM ANALYTICS.FCT_SALES_ORDER_ITEM
UNION ALL SELECT 'FCT_BILLING_ITEM', COUNT(*) FROM ANALYTICS.FCT_BILLING_ITEM
UNION ALL SELECT 'DIM_MATERIAL_CLEAN', COUNT(*) FROM ANALYTICS.DIM_MATERIAL_CLEAN
UNION ALL SELECT 'DIM_COMPANY_CODE', COUNT(*) FROM ANALYTICS.DIM_COMPANY_CODE;

-- ===================================================
-- BUSINESS QUESTIONS BEING ANSWERED 
-- ===================================================
-- 1. What is the total sales?
-- 2. Which product category has highest sale?
-- 3. Whats monnth over month sales look like?
-- 4. What is fulfillmemnt rate ? 
-- 5. What is match rate?
-- 6. What is the product with the highest profit margin?
-- 7. What is vendor concentration? 
-- 8. What is cancellation rate?
-- 9. What is PO-to-invoice cycle time?
--10. What is MAPE?

--1 What is the total sales?
SELECT 
    TO_VARCHAR(SUM(ITEM_NET_AMOUNT), '$999,999,999,999.99') AS TOTAL_SALES
FROM SAP_DB.ANALYTICS.FACT_SALES_ORDERS;

--2  Which product category has highest sale?
SELECT M.MATERIAL_GROUP, 
M.MATERIAL_DESCRIPTION, 
SUM(F.ITEM_NET_AMOUNT) AS TOTAL_SALES
FROM SAP_DB.ANALYTICS.FACT_SALES_ORDERS F 
LEFT JOIN SAP_DB.ANALYTICS.DIM_MATERIAL M 
ON F.PRODUCT_ID = M.MATERIAL_NUMBER
WHERE F.ITEM_NET_AMOUNT IS NOT NULL
GROUP BY 1,2
ORDER BY 3 DESC;


--3 Whats monnth over month sales look like?
WITH MONTHLY_SALES AS ( 
SELECT 
DATE_TRUNC('month', ORDER_DATE) AS SALES_MONTH, 
SUM(ITEM_NET_AMOUNT) AS TOTAL_SALES,
LAG(SUM(ITEM_NET_AMOUNT)) OVER (ORDER BY DATE_TRUNC('month', ORDER_DATE)) AS LAST_MONTH_SALES
FROM SAP_DB.ANALYTICS.FACT_SALES_ORDERS 
WHERE ORDER_DATE IS NOT NULL 
GROUP BY 1
) 

SELECT 
TO_VARCHAR(SALES_MONTH, 'YYYY-MM') AS MONTHL_OF_SALE,
TO_VARCHAR(TOTAL_SALES, '$999,999,999,999.99') AS CURRENT_SALES,
TO_VARCHAR(LAST_MONTH_SALES, '$999,999,999,999.99') AS PREVIOUS_SALES, 
ROUND((TOTAL_SALES - LAST_MONTH_SALES),2) MOM_DIFFERENCE, 
ROUND(((TOTAL_SALES - LAST_MONTH_SALES) / LAST_MONTH_SALES) * 100, 2) || '%' AS MOM_GROWTH_PERC
FROM MONTHLY_SALES
WHERE PREVIOUS_SALES IS NOT NULL -- As there were a few initial months with null sales.
ORDER BY MONTHL_OF_SALE DESC
LIMIT 100;

-- 4 What is fulfillmemnt rate ? -- ordershipped /orderplaced

SELECT COUNT(BILLING_ITEM) AS TOTAL_ORDER_PLACED, COUNT(
CASE WHEN IS_CANCELLED = 'X' THEN BILLING_ITEM END) AS CANCELLED_ORDER, 
ROUND(((TOTAL_ORDER_PLACED - CANCELLED_ORDER) / TOTAL_ORDER_PLACED) * 100,2) AS REPLENISHMENT_RATE
FROM ANALYTICS.FCT_BILLING_ITEM;

-- 5 What is match rate?

SELECT
    I.PO_NUMBER,
    I.PO_ITEM,
    PO.CHANGED_ON      AS PO_DATE,
    I.POSTING_DATE      AS INVOICE_DATE,
    DATEDIFF('day', PO.CHANGED_ON, I.POSTING_DATE) AS PRO2PAY_DAYS
FROM SAP_DB.ANALYTICS.FCT_AP_INVOICE_ITEM I
LEFT JOIN SAP_DB.ANALYTICS.FCT_PROCUREMENT_ITEM PO
    ON PO.PO_NUMBER = I.PO_NUMBER
   AND PO.PO_ITEM   = I.PO_ITEM
WHERE PO.CHANGED_ON IS NOT NULL
  AND DATEDIFF('day', PO.CHANGED_ON, I.POSTING_DATE) BETWEEN 0 AND 365  -- guard against bad-data outliers
ORDER BY INVOICE_DATE
LIMIT 100;

-- 6 What is the product with the highest profit margin?
-- had to use multiple joins as different vendors had the same material number. 

WITH product_margin AS (
    SELECT
        S.MATERIAL_NUMBER,
        M.MATERIAL_DESCRIPTION,
        ROUND(SUM(S.NET_AMOUNT),2)                           AS TOTAL_REVENUE,
        SUM(S.ORDER_QUANTITY)                          AS TOTAL_QUANTITY_SOLD,
        AVG(C.NET_PRICE)                               AS AVG_UNIT_COST,
        ROUND(SUM(S.ORDER_QUANTITY) * AVG(C.NET_PRICE))       AS TOTAL_COST,
        COUNT(DISTINCT S.SALES_DOC_ID)                 AS ORDER_COUNT
    FROM SAP_DB.ANALYTICS.FCT_SALES_ORDER_ITEM S
    JOIN SAP_DB.ANALYTICS.DIM_MATERIAL_CLEAN M
        ON S.MATERIAL_NUMBER = M.MATERIAL_NUMBER
    JOIN SAP_DB.ANALYTICS.FCT_PROCUREMENT_ITEM C
        ON S.MATERIAL_NUMBER = C.MATERIAL_NUMBER
       AND S.CURRENCY = C.CURRENCY
       WHERE M.MATERIAL_DESCRIPTION IS NOT NULL
    GROUP BY S.MATERIAL_NUMBER, M.MATERIAL_DESCRIPTION
)
SELECT
    MATERIAL_NUMBER,
    MATERIAL_DESCRIPTION,
    TOTAL_REVENUE,
    TOTAL_COST,
    ROUND((TOTAL_REVENUE - TOTAL_COST) / NULLIF(TOTAL_REVENUE, 0) * 100, 2) || '%' AS P_MARGIN_PCT,
    ORDER_COUNT
FROM product_margin
WHERE TOTAL_REVENUE > 0
ORDER BY P_MARGIN_PCT DESC
LIMIT 20;

-- 7. What is vendor concentration as (top 10 vendors)? (TOP10/ALL*100)

WITH TOP_VENDORS AS ( 
SELECT VENDOR_ID,
SUM(LINE_VALUE) AS VENDOR_COST
FROM ANALYTICS.FCT_PROCUREMENT_ITEM
WHERE VENDOR_ID IS NOT NULL 
AND VENDOR_ID NOT LIKE '%TEST' 
AND LINE_VALUE IS NOT NULL 
GROUP BY 1
ORDER BY 2 DESC
LIMIT 10
), 

TOTAL_COST AS ( 
SELECT SUM(LINE_VALUE) AS GRAND_COST
FROM ANALYTICS.FCT_PROCUREMENT_ITEM
) 

SELECT V.VENDOR_ID, 
V.VENDOR_COST,
ROUND ((V.VENDOR_COST/ C.GRAND_COST)* 100,2) || '%' AS PCT_OF_COST
FROM TOP_VENDORS V
JOIN TOTAL_COST C
ORDER BY PCT_OF_COST DESC
LIMIT 10;

-- 8. What is cancellation rate?

WITH CANCEL_COUNT AS (
SELECT  COUNT(BILLING_ITEM) AS TOTAL_BILLED, 
COUNT(CASE WHEN IS_CANCELLED = 'X' THEN 1 END) AS CANCELATION_COUNT
FROM ANALYTICS.FCT_BILLING_ITEM
)

SELECT TOTAL_BILLED, CANCELATION_COUNT,
(CANCELATION_COUNT/TOTAL_BILLED * 100 ) || '%' AS CANCELLATION_RATE
FROM CANCEL_COUNT;

-- Defect rate 


SELECT * FROM SAP_DB.ANALYTICS.FCT_PROCUREMENT_ITEM PO LIMIT 10;