-- =========================================================================
-- 01 -- RAW LAYER (ALL 16 TABLES)
-- Column lists below were verified directly against your uploaded CSV
-- headers (not assumed) -- each table's real source has 50-300+ columns;
-- we're deliberately loading a business-relevant subset by NAME via
-- MATCH_BY_COLUMN_NAME, not position. Extra source columns are ignored.
-- =========================================================================

USE WAREHOUSE SAP_WH;
USE DATABASE SAP_DB;
USE SCHEMA RAW;

-- =========================================================================
-- O2C: Sales
-- =========================================================================


CREATE OR REPLACE TABLE RAW.VBAK (
    MANDT VARCHAR, VBELN VARCHAR, ERDAT VARCHAR, ERZET VARCHAR, ERNAM VARCHAR,
    ANGDT VARCHAR, BNDDT VARCHAR, AUDAT VARCHAR, VBTYP VARCHAR, TRVOG VARCHAR,
    AUART VARCHAR, AUGRU VARCHAR, NETWR VARCHAR, WAERK VARCHAR, VKORG VARCHAR
);

COPY INTO RAW.VBAK FROM @SAP_DB.RAW.SAP_RAW_STAGE/vbak.csv
FILE_FORMAT = (
    FORMAT_NAME = SAP_CSV_FORMAT, 
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
) 
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE 
ON_ERROR = 'CONTINUE';

-- SELECT * FROM RAW.VBAK LIMIT 10;

CREATE OR REPLACE TABLE RAW.VBAP (
    MANDT VARCHAR, VBELN VARCHAR, POSNR VARCHAR, MATNR VARCHAR, MATWA VARCHAR,
    PMATN VARCHAR, CHARG VARCHAR, MATKL VARCHAR, ARKTX VARCHAR, PSTYV VARCHAR,
    NETWR VARCHAR, WAERK VARCHAR, KWMENG VARCHAR, VRKME VARCHAR, WERKS VARCHAR, NETPR VARCHAR
);
COPY INTO RAW.VBAP FROM @SAP_DB.RAW.SAP_RAW_STAGE/vbap.csv
FILE_FORMAT = (
    FORMAT_NAME = SAP_CSV_FORMAT, 
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
) 
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE 
ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE RAW.VBRK (
    MANDT VARCHAR, VBELN VARCHAR, FKART VARCHAR, FKTYP VARCHAR, VBTYP VARCHAR,
    WAERK VARCHAR, VKORG VARCHAR, FKDAT VARCHAR, BELNR VARCHAR, GJAHR VARCHAR,
    NETWR VARCHAR, FKSTO VARCHAR, KUNAG VARCHAR, BUKRS VARCHAR
);
COPY INTO RAW.VBRK FROM @SAP_DB.RAW.SAP_RAW_STAGE/vbrk.csv
FILE_FORMAT = (
    FORMAT_NAME = SAP_CSV_FORMAT, 
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
) 
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE 
ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE RAW.VBRP (
    MANDT VARCHAR, VBELN VARCHAR, POSNR VARCHAR, FKIMG VARCHAR, VRKME VARCHAR,
    MEINS VARCHAR, NETWR VARCHAR, VGBEL VARCHAR, VGPOS VARCHAR, MATNR VARCHAR,
    ARKTX VARCHAR, WERKS VARCHAR
);

COPY INTO RAW.VBRP FROM @SAP_DB.RAW.SAP_RAW_STAGE/vbrp.csv
FILE_FORMAT = (
    FORMAT_NAME = SAP_CSV_FORMAT, 
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
) 
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE 
ON_ERROR = 'CONTINUE';

-- =========================================================================
-- P2P: Procurement
-- =========================================================================

CREATE OR REPLACE TABLE RAW.EKKO (
    MANDT VARCHAR, EBELN VARCHAR, BUKRS VARCHAR, BSTYP VARCHAR, BSART VARCHAR,
    STATU VARCHAR, AEDAT VARCHAR, ERNAM VARCHAR, LIFNR VARCHAR, WAERS VARCHAR,
    EKORG VARCHAR, EKGRP VARCHAR
);

COPY INTO RAW.EKKO FROM @SAP_DB.RAW.SAP_RAW_STAGE/ekko.csv
FILE_FORMAT = (
    FORMAT_NAME = SAP_CSV_FORMAT, 
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
) 
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE 
ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE RAW.EKPO (
    MANDT VARCHAR, EBELN VARCHAR, EBELP VARCHAR, MATNR VARCHAR, BUKRS VARCHAR,
    WERKS VARCHAR, LGORT VARCHAR, MENGE VARCHAR, MEINS VARCHAR, NETPR VARCHAR,
    NETWR VARCHAR, MATKL VARCHAR
);

COPY INTO RAW.EKPO FROM @SAP_DB.RAW.SAP_RAW_STAGE/ekpo.csv
FILE_FORMAT = (
    FORMAT_NAME = SAP_CSV_FORMAT, 
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
) 
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE 
ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE RAW.RBKP (
    MANDT VARCHAR, BELNR VARCHAR, GJAHR VARCHAR, BLART VARCHAR, BLDAT VARCHAR,
    BUDAT VARCHAR, CPUDT VARCHAR, USNAM VARCHAR, LIFNR VARCHAR, WAERS VARCHAR,
    RMWWR VARCHAR, BUKRS VARCHAR
);

COPY INTO RAW.RBKP FROM @SAP_DB.RAW.SAP_RAW_STAGE/rbkp.csv
FILE_FORMAT = (
    FORMAT_NAME = SAP_CSV_FORMAT, 
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
) 
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE 
ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE RAW.RSEG (
    MANDT VARCHAR, BELNR VARCHAR, GJAHR VARCHAR, BUZEI VARCHAR, EBELN VARCHAR,
    EBELP VARCHAR, MATNR VARCHAR, WRBTR VARCHAR, SHKZG VARCHAR, WERKS VARCHAR, MENGE VARCHAR
);

COPY INTO RAW.RSEG FROM @SAP_DB.RAW.SAP_RAW_STAGE/rseg.csv
FILE_FORMAT = (
    FORMAT_NAME = SAP_CSV_FORMAT, 
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
) 
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE 
ON_ERROR = 'CONTINUE';

-- =========================================================================
-- MASTER DATA
-- =========================================================================

CREATE OR REPLACE TABLE RAW.CSKS (
    MANDT VARCHAR, KOKRS VARCHAR, KOSTL VARCHAR, DATBI VARCHAR, DATAB VARCHAR,
    BUKRS VARCHAR, GSBER VARCHAR, KOSAR VARCHAR, VERAK VARCHAR, WERKS VARCHAR
);

COPY INTO RAW.CSKS FROM @SAP_DB.RAW.SAP_RAW_STAGE/csks.csv
FILE_FORMAT = (
    FORMAT_NAME = SAP_CSV_FORMAT, 
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
) 
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE 
ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE RAW.CSKT (
    MANDT VARCHAR, SPRAS VARCHAR, KOKRS VARCHAR, KOSTL VARCHAR, DATBI VARCHAR,
    KTEXT VARCHAR, LTEXT VARCHAR
);

COPY INTO RAW.CSKT FROM @SAP_DB.RAW.SAP_RAW_STAGE/cskt.csv
FILE_FORMAT = (
    FORMAT_NAME = SAP_CSV_FORMAT, 
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
) 
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE 
ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE RAW.MAKT (
    MANDT VARCHAR, MATNR VARCHAR, SPRAS VARCHAR, MAKTX VARCHAR, MAKTG VARCHAR
);

COPY INTO RAW.MAKT FROM @SAP_DB.RAW.SAP_RAW_STAGE/makt.csv
FILE_FORMAT = (
    FORMAT_NAME = SAP_CSV_FORMAT, 
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
) 
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE 
ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE RAW.MARA (
    MANDT VARCHAR, MATNR VARCHAR, ERSDA VARCHAR, ERNAM VARCHAR, LAEDA VARCHAR,
    MTART VARCHAR, MBRSH VARCHAR, MATKL VARCHAR, MEINS VARCHAR, BRGEW VARCHAR,
    NTGEW VARCHAR, GEWEI VARCHAR
);

COPY INTO RAW.MARA FROM @SAP_DB.RAW.SAP_RAW_STAGE/mara.csv
FILE_FORMAT = (
    FORMAT_NAME = SAP_CSV_FORMAT, 
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE //don't stop if we are loading selected columns 
) 
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE  // match the column by name not by index 
ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE RAW.MARD (
    MANDT VARCHAR, MATNR VARCHAR, WERKS VARCHAR, LGORT VARCHAR, LABST VARCHAR,
    INSME VARCHAR, SPEME VARCHAR
);

COPY INTO RAW.MARD FROM @SAP_DB.RAW.SAP_RAW_STAGE/mard.csv
FILE_FORMAT = (
    FORMAT_NAME = SAP_CSV_FORMAT, 
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
) 
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE 
ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE RAW.T001 (
    MANDT VARCHAR, BUKRS VARCHAR, BUTXT VARCHAR, ORT01 VARCHAR, LAND1 VARCHAR,
    WAERS VARCHAR, SPRAS VARCHAR
);

COPY INTO RAW.T001 FROM @SAP_DB.RAW.SAP_RAW_STAGE/t001.csv
FILE_FORMAT = (
    FORMAT_NAME = SAP_CSV_FORMAT, 
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
) 
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE 
ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE RAW.T002 (
    SPRAS VARCHAR, LAISO VARCHAR
);

COPY INTO RAW.T002 FROM @SAP_DB.RAW.SAP_RAW_STAGE/t002.csv
FILE_FORMAT = (
    FORMAT_NAME = SAP_CSV_FORMAT, 
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
) 
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE 
ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE RAW.TCURR (
    MANDT VARCHAR, KURST VARCHAR, FCURR VARCHAR, TCURR VARCHAR, GDATU VARCHAR, UKURS VARCHAR
);

COPY INTO RAW.TCURR FROM @SAP_DB.RAW.SAP_RAW_STAGE/tcurr.csv
FILE_FORMAT = (
    FORMAT_NAME = SAP_CSV_FORMAT, 
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
) 
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE 
ON_ERROR = 'CONTINUE';
-- -------------------------------------------------------------------------
-- Verify: row counts + non-null counts on the fields that broke last time
-- -------------------------------------------------------------------------
SELECT 'VBAK' T, COUNT(*) ROW_COUNT, COUNT(NETWR) NETWR_OK, COUNT(WAERK) WAERK_OK FROM RAW.VBAK
UNION ALL SELECT 'VBAP', COUNT(*), COUNT(NETWR), COUNT(KWMENG) FROM RAW.VBAP
UNION ALL SELECT 'VBRK', COUNT(*), COUNT(NETWR), NULL FROM RAW.VBRK
UNION ALL SELECT 'VBRP', COUNT(*), COUNT(NETWR), NULL FROM RAW.VBRP
UNION ALL SELECT 'EKKO', COUNT(*), NULL, COUNT(WAERS) FROM RAW.EKKO
UNION ALL SELECT 'EKPO', COUNT(*), COUNT(NETPR), COUNT(MENGE) FROM RAW.EKPO
UNION ALL SELECT 'RBKP', COUNT(*), COUNT(RMWWR), NULL FROM RAW.RBKP
UNION ALL SELECT 'RSEG', COUNT(*), COUNT(WRBTR), NULL FROM RAW.RSEG
UNION ALL SELECT 'CSKS', COUNT(*), NULL, NULL FROM RAW.CSKS
UNION ALL SELECT 'CSKT', COUNT(*), NULL, NULL FROM RAW.CSKT
UNION ALL SELECT 'MAKT', COUNT(*), NULL, NULL FROM RAW.MAKT
UNION ALL SELECT 'MARA', COUNT(*), NULL, NULL FROM RAW.MARA
UNION ALL SELECT 'MARD', COUNT(*), NULL, NULL FROM RAW.MARD
UNION ALL SELECT 'T001', COUNT(*), NULL, NULL FROM RAW.T001
UNION ALL SELECT 'T002', COUNT(*), NULL, NULL FROM RAW.T002
UNION ALL SELECT 'TCURR', COUNT(*), NULL, NULL FROM RAW.TCURR;

--- DBT ADD ONS 
USE WAREHOUSE SAP_WH;
USE DATABASE SAP_DB;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW.EKKO (
    MANDT VARCHAR, EBELN VARCHAR, BUKRS VARCHAR, BSTYP VARCHAR, BSART VARCHAR,
    STATU VARCHAR, AEDAT VARCHAR, BEDAT VARCHAR, ERNAM VARCHAR, LIFNR VARCHAR, WAERS VARCHAR,
    EKORG VARCHAR, EKGRP VARCHAR
);

COPY INTO RAW.EKKO FROM @SAP_DB.RAW.SAP_RAW_STAGE/ekko.csv
FILE_FORMAT = (FORMAT_NAME = SAP_CSV_FORMAT)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'CONTINUE';

-- confirm BEDAT is now populated
USE WAREHOUSE SAP_WH;
USE DATABASE SAP_DB;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW.EKKO (
    MANDT VARCHAR, EBELN VARCHAR, BUKRS VARCHAR, BSTYP VARCHAR, BSART VARCHAR,
    STATU VARCHAR, AEDAT VARCHAR, BEDAT VARCHAR, ERNAM VARCHAR, LIFNR VARCHAR, WAERS VARCHAR,
    EKORG VARCHAR, EKGRP VARCHAR
);

DESCRIBE TABLE RAW.EKKO;

COPY INTO RAW.EKKO FROM @SAP_DB.RAW.SAP_RAW_STAGE/ekko.csv
FILE_FORMAT = (FORMAT_NAME = SAP_CSV_FORMAT, ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'CONTINUE';

SELECT COUNT(*) AS total_rows, COUNT(BEDAT) AS bedat_populated
FROM RAW.EKKO;
